[tool.poetry]
name = "youtube-analytics"
version = "0.1.0"
description = ""
authors = ["Grandic <d.bitkov@gmail.com>"]
readme = "README.md"
packages = [{include = "youtube_analytics"}]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
